### PR TITLE
Fix the map loading state.

### LINKED ISSUE #171: Project Loading State Is Ignored
Duckling is supposed to show a loading screen as the map is loaded. This doesn't happen. It instead displays an empty map and then draws the entities once the map is loaded.

### PR DESCRIPTION
**Pull request by jeffswenson**
Resolves #171

### CODE REVIEW

File: src/duckling/shell/shell.component.ts [hunk 1]
```diff
@@ -18,16 +18,16 @@ import {StoreService} from '../state';
 
 @Component({
     selector: 'dk-shell',
-    styleUrls: ['./duckling/shell/shell.component.css'],
+    styleUrls: ['./duckling/shell/shell.component.css', './duckling/layout.css'],
```
Comment (tlein) [inline src/duckling/shell/shell.component.ts]: You should import layout into the shell.component.scss file instead of referencing it here
